# Generated by Django 3.2.7 on 2021-09-28 01:07

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=150)),
                ('certidao', models.CharField(default='0000000000000', help_text='Número da certidão de nascimento', max_length=33, unique=True)),
                ('mae', models.CharField(blank=True, max_length=150, null=True)),
                ('pai', models.CharField(blank=True, max_length=150, null=True)),
                ('tel1', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Telefone da mãe', max_length=128, null=True, region=None, unique=True)),
                ('tel2', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Telefone do pai ou responsável', max_length=128, null=True, region=None, unique=True)),
                ('endereco', models.CharField(max_length=250)),
                ('email', models.EmailField(help_text='email', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Boletim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretaria.aluno')),
            ],
            options={
                'verbose_name': 'Boletim',
                'verbose_name_plural': 'Boletins',
                'ordering': ('-aluno',),
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=150)),
                ('admissao', models.DateField(auto_now_add=True, null=True, verbose_name='Data de admissão')),
                ('disciplina', models.ManyToManyField(blank=True, help_text='Escolha as disciplinas ministradas pelo professor e transfira para a tabela da direita.', to='secretaria.Materia')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ensino', models.CharField(choices=[('Educacao Infantil', (('EI-CRE', 'EI-Creche'), ('EI-GP1', 'EI-Grupo 1'), ('EI-GP2', 'EI-Grupo 2'), ('EI-GP3', 'EI-Grupo 3'), ('EI-GP4', 'EI-Grupo 4'), ('EI-GP5', 'EI-Grupo 5'))), ('Educacao Fundamental I', (('1-EFI', '1º Ano EFI'), ('2-EFI', '2º Ano EFI'), ('3-EFI', '3º Ano EFI'), ('4-EFI', '4º Ano EFI'), ('5-EFI', '5º Ano EFI'))), ('Educacao Fundamental II', (('6-EFII', '6º Ano EFII'), ('7-EFII', '7º Ano EFII'), ('8-EFII', '8º Ano EFII'), ('9-EFII', '9º Ano EFII'))), ('Ensino Medio', (('1-MED', '1º Ano Medio'), ('2-MED', '2º Ano Medio'), ('3-MED', '3º Ano Medio')))], max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
                'ordering': ('ensino',),
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(choices=[('A', 'Alfa'), ('B', 'Bravo'), ('C', 'Charlie'), ('D', 'Delta')], max_length=100)),
                ('turno', models.CharField(choices=[('M', 'Manha'), ('T', 'Tarde'), ('N', 'Noite')], max_length=100)),
                ('ano', models.IntegerField(default=2020, help_text='ex:2021', verbose_name='Ano da turma')),
                ('prof', models.ManyToManyField(blank=True, help_text='Escolha os professores e transfira para a tabela da direita. ', to='secretaria.Professor', verbose_name='Professor')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretaria.serie')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ('-ano',),
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.FloatField(default=0)),
                ('nota2', models.FloatField(default=0)),
                ('nota3', models.FloatField(default=0)),
                ('media', models.FloatField(default=0)),
                ('boletim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretaria.boletim')),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretaria.materia')),
            ],
        ),
        migrations.AddField(
            model_name='boletim',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretaria.turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='classe',
            field=models.ForeignKey(blank=True, help_text='Turma que o aluno esta atualmente cursando', null=True, on_delete=django.db.models.deletion.CASCADE, to='secretaria.turma'),
        ),
    ]
