# Generated by Django 3.2.7 on 2021-09-28 19:20

from django.db import migrations, models
import django_cpf_cnpj.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=django_cpf_cnpj.fields.CPFField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='tel2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Telefone do pai ou responsável financeiro', max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='classe',
            field=models.CharField(choices=[('A', 'Alfa'), ('B', 'Bravo'), ('C', 'Charlie'), ('D', 'Delta')], default='Alfa', max_length=100),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turno',
            field=models.CharField(choices=[('M', 'Manha'), ('T', 'Tarde'), ('N', 'Noite')], default='Manha', max_length=100),
        ),
    ]
