# Generated by Django 3.2.7 on 2021-09-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0004_remove_info_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='certidao',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='mae',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='pai',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='tel1',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='tel2',
        ),
    ]
