# Generated by Django 3.2.7 on 2021-09-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0005_auto_20210929_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Dados Pessoais', 'verbose_name_plural': 'Informações Pessoais'},
        ),
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.EmailField(help_text='email do responsável financeiro', max_length=200),
        ),
    ]
