# Generated by Django 3.2.7 on 2021-09-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0006_auto_20210929_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boletim',
            options={'ordering': ('aluno',), 'verbose_name': 'Boletim', 'verbose_name_plural': 'Boletins'},
        ),
        migrations.AlterField(
            model_name='turma',
            name='ano',
            field=models.IntegerField(default=2021, help_text='ex:2021', verbose_name='Ano da turma'),
        ),
    ]
